services:
  - type: web
    plan: free
    name: Yogesh
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python3 main.py
    repo: https://github.com/yogesh313r/link.git      
    branch: main
    envVars:
      - key: BOT_TOKEN 
        sync: false
      - key: API_ID 
        sync: false
      - key: API_HASH
        sync: false
      - key: ADMINS
        sync: false
      - key: DATABASE_NAME
        sync: false
      - key: DATABASE_URI
        sync: false
      - key: OWNER 
        sync: false
      - key: LOG_CHANNEL
        sync: false
      - key: FORCE_SUB
        sync: false
    autoDeploy: false
